
services:
  db:
    image: postgres:15-alpine
    container_name: verse-db
    environment:
      POSTGRES_USER: verse_user
      POSTGRES_PASSWORD: verse_password
      POSTGRES_DB: verse_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U verse_user -d verse_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: verse-backend
    environment:
      DATABASE_URL: postgresql://verse_user:verse_password@db:5432/verse_db
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      ENVIRONMENT: development
      DEBUG: "true"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: verse-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    command: bun run dev --host 0.0.0.0

volumes:
  postgres_data:
  frontend_node_modules:
