"""initial_schema

Revision ID: d0d22a6e1dc8
Revises:
Create Date: 2025-12-06 19:27:05.536604

"""

from collections.abc import Sequence

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d0d22a6e1dc8"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pgvector extension
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation_summaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_type", sa.String(length=20), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("summary_text", sa.Text(), nullable=False),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_conversation_lookup",
        "conversation_summaries",
        ["conversation_type", "conversation_id"],
        unique=True,
    )
    op.create_index(op.f("ix_conversation_summaries_id"), "conversation_summaries", ["id"], unique=False)
    op.create_table(
        "saved_definitions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("word", sa.String(length=100), nullable=False),
        sa.Column("passage_reference", sa.String(length=100), nullable=False),
        sa.Column("verse_text", sa.Text(), nullable=False),
        sa.Column("definition", sa.Text(), nullable=False),
        sa.Column("biblical_usage", sa.Text(), nullable=False),
        sa.Column("original_language", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("word", "passage_reference", "verse_text", name="uix_word_reference_verse"),
    )
    op.create_index("idx_word", "saved_definitions", ["word"], unique=False)
    op.create_index(op.f("ix_saved_definitions_id"), "saved_definitions", ["id"], unique=False)
    op.create_index(
        op.f("ix_saved_definitions_passage_reference"),
        "saved_definitions",
        ["passage_reference"],
        unique=False,
    )
    op.create_index(op.f("ix_saved_definitions_word"), "saved_definitions", ["word"], unique=False)
    op.create_table(
        "saved_insights",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("passage_reference", sa.String(length=100), nullable=False),
        sa.Column("passage_text", sa.Text(), nullable=False),
        sa.Column("historical_context", sa.Text(), nullable=False),
        sa.Column("theological_significance", sa.Text(), nullable=False),
        sa.Column("practical_application", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("passage_reference", "passage_text", name="uix_passage_reference_text"),
    )
    op.create_index("idx_passage_text", "saved_insights", ["passage_text"], unique=False)
    op.create_index(op.f("ix_saved_insights_id"), "saved_insights", ["id"], unique=False)
    op.create_index(
        op.f("ix_saved_insights_passage_reference"), "saved_insights", ["passage_reference"], unique=False
    )
    op.create_table(
        "saved_passages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reference", sa.String(length=100), nullable=False),
        sa.Column("book", sa.String(length=50), nullable=False),
        sa.Column("chapter", sa.Integer(), nullable=False),
        sa.Column("verse_start", sa.Integer(), nullable=False),
        sa.Column("verse_end", sa.Integer(), nullable=True),
        sa.Column("translation", sa.String(length=10), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_saved_passages_id"), "saved_passages", ["id"], unique=False)
    op.create_index(op.f("ix_saved_passages_reference"), "saved_passages", ["reference"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("anonymous_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("device_count", sa.Integer(), nullable=False),
        sa.Column("pro_subscription", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_anonymous_id"), "users", ["anonymous_id"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("insight_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("was_truncated", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("embedding", Vector(1536), nullable=True),
        sa.ForeignKeyConstraint(["insight_id"], ["saved_insights.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_chat_messages_embedding_user",
        "chat_messages",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        "idx_chat_messages_insight_user_created",
        "chat_messages",
        ["insight_id", "user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_chat_messages_user_created", "chat_messages", ["user_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_chat_messages_id"), "chat_messages", ["id"], unique=False)
    op.create_index(op.f("ix_chat_messages_insight_id"), "chat_messages", ["insight_id"], unique=False)
    op.create_index(op.f("ix_chat_messages_user_id"), "chat_messages", ["user_id"], unique=False)
    op.create_table(
        "standalone_chats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("passage_reference", sa.String(length=100), nullable=True),
        sa.Column("passage_text", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_standalone_chats_user_updated", "standalone_chats", ["user_id", "updated_at"], unique=False
    )
    op.create_index(op.f("ix_standalone_chats_id"), "standalone_chats", ["id"], unique=False)
    op.create_index(op.f("ix_standalone_chats_user_id"), "standalone_chats", ["user_id"], unique=False)
    op.create_table(
        "usage_tracking",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("llm_calls", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "date", name="uix_user_date"),
    )
    op.create_index("idx_usage_tracking_user_date", "usage_tracking", ["user_id", "date"], unique=False)
    op.create_index(op.f("ix_usage_tracking_date"), "usage_tracking", ["date"], unique=False)
    op.create_index(op.f("ix_usage_tracking_id"), "usage_tracking", ["id"], unique=False)
    op.create_index(op.f("ix_usage_tracking_user_id"), "usage_tracking", ["user_id"], unique=False)
    op.create_table(
        "user_definitions",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("definition_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["definition_id"], ["saved_definitions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "definition_id"),
    )
    op.create_index(
        "idx_user_definitions_user_created", "user_definitions", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "user_devices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("device_name", sa.String(length=100), nullable=True),
        sa.Column("device_type", sa.String(length=20), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("last_active", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_user_devices_last_active", "user_devices", ["user_id", "last_active"], unique=False)
    op.create_index(op.f("ix_user_devices_id"), "user_devices", ["id"], unique=False)
    op.create_index(op.f("ix_user_devices_user_id"), "user_devices", ["user_id"], unique=False)
    op.create_table(
        "user_insights",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("insight_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["insight_id"], ["saved_insights.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "insight_id"),
    )
    op.create_index(
        "idx_user_insights_user_created", "user_insights", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "device_link_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("display_code", sa.String(length=20), nullable=False),
        sa.Column("source_user_id", sa.Integer(), nullable=False),
        sa.Column("source_device_id", sa.Integer(), nullable=True),
        sa.Column("target_user_id", sa.Integer(), nullable=True),
        sa.Column("target_device_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(["source_device_id"], ["user_devices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_device_id"], ["user_devices.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["target_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_device_link_codes_code"), "device_link_codes", ["code"], unique=True)
    op.create_index(
        op.f("ix_device_link_codes_display_code"), "device_link_codes", ["display_code"], unique=True
    )
    op.create_index(op.f("ix_device_link_codes_id"), "device_link_codes", ["id"], unique=False)
    op.create_index(
        op.f("ix_device_link_codes_source_user_id"), "device_link_codes", ["source_user_id"], unique=False
    )
    op.create_table(
        "standalone_chat_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("was_truncated", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("embedding", Vector(1536), nullable=True),
        sa.ForeignKeyConstraint(["chat_id"], ["standalone_chats.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_standalone_messages_embedding",
        "standalone_chat_messages",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        op.f("ix_standalone_chat_messages_chat_id"), "standalone_chat_messages", ["chat_id"], unique=False
    )
    op.create_index(op.f("ix_standalone_chat_messages_id"), "standalone_chat_messages", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_standalone_chat_messages_id"), table_name="standalone_chat_messages")
    op.drop_index(op.f("ix_standalone_chat_messages_chat_id"), table_name="standalone_chat_messages")
    op.drop_index(
        "idx_standalone_messages_embedding",
        table_name="standalone_chat_messages",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("standalone_chat_messages")
    op.drop_index(op.f("ix_device_link_codes_source_user_id"), table_name="device_link_codes")
    op.drop_index(op.f("ix_device_link_codes_id"), table_name="device_link_codes")
    op.drop_index(op.f("ix_device_link_codes_display_code"), table_name="device_link_codes")
    op.drop_index(op.f("ix_device_link_codes_code"), table_name="device_link_codes")
    op.drop_table("device_link_codes")
    op.drop_index("idx_user_insights_user_created", table_name="user_insights")
    op.drop_table("user_insights")
    op.drop_index(op.f("ix_user_devices_user_id"), table_name="user_devices")
    op.drop_index(op.f("ix_user_devices_id"), table_name="user_devices")
    op.drop_index("idx_user_devices_last_active", table_name="user_devices")
    op.drop_table("user_devices")
    op.drop_index("idx_user_definitions_user_created", table_name="user_definitions")
    op.drop_table("user_definitions")
    op.drop_index(op.f("ix_usage_tracking_user_id"), table_name="usage_tracking")
    op.drop_index(op.f("ix_usage_tracking_id"), table_name="usage_tracking")
    op.drop_index(op.f("ix_usage_tracking_date"), table_name="usage_tracking")
    op.drop_index("idx_usage_tracking_user_date", table_name="usage_tracking")
    op.drop_table("usage_tracking")
    op.drop_index(op.f("ix_standalone_chats_user_id"), table_name="standalone_chats")
    op.drop_index(op.f("ix_standalone_chats_id"), table_name="standalone_chats")
    op.drop_index("idx_standalone_chats_user_updated", table_name="standalone_chats")
    op.drop_table("standalone_chats")
    op.drop_index(op.f("ix_chat_messages_user_id"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_insight_id"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_id"), table_name="chat_messages")
    op.drop_index("idx_chat_messages_user_created", table_name="chat_messages")
    op.drop_index("idx_chat_messages_insight_user_created", table_name="chat_messages")
    op.drop_index(
        "idx_chat_messages_embedding_user",
        table_name="chat_messages",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("chat_messages")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_anonymous_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_saved_passages_reference"), table_name="saved_passages")
    op.drop_index(op.f("ix_saved_passages_id"), table_name="saved_passages")
    op.drop_table("saved_passages")
    op.drop_index(op.f("ix_saved_insights_passage_reference"), table_name="saved_insights")
    op.drop_index(op.f("ix_saved_insights_id"), table_name="saved_insights")
    op.drop_index("idx_passage_text", table_name="saved_insights")
    op.drop_table("saved_insights")
    op.drop_index(op.f("ix_saved_definitions_word"), table_name="saved_definitions")
    op.drop_index(op.f("ix_saved_definitions_passage_reference"), table_name="saved_definitions")
    op.drop_index(op.f("ix_saved_definitions_id"), table_name="saved_definitions")
    op.drop_index("idx_word", table_name="saved_definitions")
    op.drop_table("saved_definitions")
    op.drop_index(op.f("ix_conversation_summaries_id"), table_name="conversation_summaries")
    op.drop_index("idx_conversation_lookup", table_name="conversation_summaries")
    op.drop_table("conversation_summaries")
    # ### end Alembic commands ###
